name: Deploy
          
on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@master
      
      - name: git status
        run: git status -uno --porcelain
        
      - name: git reset
        run: git reset --hard
        
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp://185.224.137.142
          server-dir: /home/u878187079/domains/forgeit.qa/lug/
          username: ${{ secrets.FTP_ADMIN }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
