name: Deploy

on:
  push:
    branches: [ master, main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.bosniansunited.com
          server-dir: domains/forgeit/public_html/lug/
          username: ${{ secrets.FTP_ADMIN }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: /
